const products = [
  {
    id: 2,
    name: " Nike Zoom KD 4",
    imageSrc: "/img/product2.jpg",
    imageAlt: "Shoes.",
    price: 35000.0,
    color: ["Green", "purple", "gray", "pink"],
    sizes: ["45", "46", "42", "40", "44"],
    description:
      "When the Zoom KD 4 debuted in 2011, it marked a clear shift in Kevin Durant’s signature line. Up to that point, Durant was living up to the hype with his on-court play, but it didn’t result in many memorable sneakers. ",
    highlights: [
      "Durable Sole",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100%",
    ],
  },
  {
    id: 3,
    name: " Nike Roshe",
    imageSrc: "/img/product3.jpg",
    imageAlt: "Shoes.",
    price: 100000.0,
    color: ["Green", "purple", "gray", "pink"],
    sizes: ["45", "46", "42", "40", "44"],
    description:
      "The Nike Roshe Run, the shoe’s original name when it debuted in 2012, wasn’t like much on the market at the time. The sole was a one-piece foam and the upper was an airy, loose-gauge mesh with a glued-on Swoosh.",
    highlights: [
      "Durable Sole",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100%",
    ],
  },
  {
    id: 1,
    name: "Nike Air Jordan 1",
    imageSrc: "/img/product1.jpg",
    imageAlt: "Shoes.",
    price: 20000.0,
    color: ["Green", "purple", "gray", "pink"],
    sizes: ["45", "46", "42", "40", "44"],
    description:
      "There’s not much that can be said about the Air Jordan 1 that hasn’t been said already. Everyone knows the story: Michael Jordan was selected by the Chicago Bulls with the third pick in the 1984 NBA Draft out of the University of North Carolina. ",
    highlights: [
      "Durable Sole",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100%",
    ],
  },
  {
    id: 4,
    name: "Nike Air Zoom Huarache 2K4",
    imageSrc: "/img/product4.jpg",
    imageAlt: "Shoes.",
    price: 55000.0,
    color: ["Green", "purple", "gray", "pink"],
    sizes: ["45", "46", "42", "40", "44"],
    description:
      "Before the official Nike Kobe line that redefined performance basketball footwear as we know it, we had the Huarache 2K4. The silhouette was the unofficial signature shoe of the late Kobe Bryant upon signing with Nike in 2003.",
    highlights: [
      "Durable Sole",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100%",
    ],
  },
  {
    id: 5,
    name: " Nike Waffle Racer",
    imageSrc: "/img/product5.jpg",
    imageAlt: "Shoes.",
    price: 65000.0,
    color: ["Green", "purple", "gray", "pink"],
    sizes: ["45", "46", "42", "40", "44"],
    description:
      "The Nike Waffle Racer is a shoe of lore. On this list not because it’s a favorite amongst today’s era of sneakerheads, but because it’s one of Nike’s most important sneakers ever. Before Air Max, before Air Jordan, before Air Force 1, there was Nike’s Waffle sole. ",
    highlights: [
      "Durable Sole",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100%",
    ],
  },
  {
    id: 6,
    name: "Nike Air Zoom ",
    imageSrc: "/img/product6.jpg",
    imageAlt: "Shoes.",
    price: 85000.0,
    color: ["Green", "purple", "gray", "pink"],
    sizes: ["45", "46", "42", "40", "44"],
    description:
      "After signing 18-year-old LeBron James to a then-record seven-year, $90 million contract in 2003, Nike was left with the task of creating a debut signature shoe for a generational athlete and arguably the most hyped NBA prospect of all-time. ",
    highlights: [
      "Durable Sole",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100%",
    ],
  },
  {
    id: 7,
    name: "Nike Air Force 1",
    imageSrc: "/img/product7.jpg",
    imageAlt: "Shoes.",
    price: 200000.0,
    color: ["Green", "purple", "gray", "pink"],
    sizes: ["45", "46", "42", "40", "44"],
    description:
      "Introduced as a high-top in 1982, and followed by the release of its low-top form in 1983, the Air Force 1 was Nike’s first basketball shoe to use the brand’s signature Air cushioning technology. Despite being groundbreaking in that regard, Nike planned to put an end to the sneaker’s production in 1984. ",
    highlights: [
      "Durable Sole",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100%",
    ],
  },
  {
    id: 8,
    name: " Nike Air Max 1",
    imageSrc: "/img/product8.jpg",
    imageAlt: "Shoes.",
    price: 90000.0,
    color: ["Green", "purple", "gray", "pink"],
    sizes: ["45", "46", "42", "40", "44"],
    description:
      "In 1978, Nike released the Air Tailwind, a running shoe infused with its new Air cushioning system. The innovation was the idea of an aerospace engineer named Frank Rudy, who presented Nike co-founder Phil Knight with the then-radical concept of the gas-filled urethane pouches a year earlier. ",
    highlights: [
      "Durable Sole",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100%",
    ],
  },
  {
    id: 9,
    name: "Nike Air Jordan 3",
    imageSrc: "/img/product9.jpg",
    imageAlt: "Shoes.",
    price: 125000.0,
    color: ["Green", "purple", "gray", "pink"],
    sizes: ["45", "46", "42", "40", "44"],
    description:
      "Tinker Hatfield’s back was against the wall going into the creation of the shoe in 1987. Michael Jordan was unhappy with his previous shoe, the Air Jordan 2 (designed by Peter Moore and Bruce Kilgore), after spending much of the 1985-’86 season sidelined with a broken foot sustained while wearing it. ",
    highlights: [
      "Durable Sole",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100%",
    ],
  },
  {
    id: 10,
    name: "Nike Dunk",
    imageSrc: "/img/product10.jpg",
    imageAlt: "Shoes.",
    price: 45000.0,
    color: ["Green", "purple", "gray", "pink"],
    sizes: ["45", "46", "42", "40", "44"],
    description:
      "The Nike Dunk is the ultimate storytelling canvas in sneaker form. The Dunk’s ability to evolve and host some of the most creative applications of colors, materials, textures, and prints has cemented them as an immensely important shoe that has become a de facto voice of the people, telling athletes’, collaborators’, and artists’ stories since their initial launch in 1985. ",
    highlights: [
      "Durable Sole",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100%",
    ],
  },
  {
    id: 11,
    name: "Nike Air Jordan 11",
    imageSrc: "/img/product11.jpg",
    imageAlt: "Shoes.",
    price: 145000.0,
    color: ["Green", "purple", "gray", "pink"],
    sizes: ["45", "46", "42", "40", "44"],
    description:
      "If you step into a room wearing a pair of Air Jordan 11s, odds are all eyes will be on your feet. Decades after their initial release, the sneaker still carries an air of prestige that commands attention. Sneaker designer Tinker Hatfield’s magic formula of patent leather, ballistic mesh, and clear soles turned what could have been an over-the-top mess into a masterpiece. ",
    highlights: [
      "Durable Sole",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100%",
    ],
  },
  {
    id: 12,
    name: "Nike Air Zoom Generation",
    imageSrc: "/img/product12.jpg",
    imageAlt: "Shoes.",
    price: 78000.0,
    color: ["Green", "purple", "gray", "pink"],
    sizes: ["45", "46", "42", "40", "44"],
    description:
      "After signing 18-year-old LeBron James to a then-record seven-year, $90 million contract in 2003, Nike was left with the task of creating a debut signature shoe for a generational athlete and arguably the most hyped NBA prospect of all-time. ",
    highlights: [
      "Durable Sole",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100%",
    ],
  },
  {
    id: 13,
    name: "Nike Air Jordan 1",
    imageSrc: "/img/product5.jpg",
    imageAlt: "Shoes.",
    price: 205000.0,
    color: ["Green", "purple", "gray", "pink"],
    sizes: ["45", "46", "42", "40", "44"],
    description:
      "The Air Jordan 4 shares many physical characteristics with its predecessor, without the prestige of being the shoe that prevented Michael Jordan from leaving Nike. In that context, it’s understandable that it would fall behind the Air Jordan 3 in terms of the greatest",
    highlights: [
      "Durable Sole",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100%",
    ],
  },
  {
    id: 14,
    name: "Nike Air Max 95",
    imageSrc: "/img/product2.jpg",
    imageAlt: "Shoes.",
    price: 85000.0,
    color: ["Green", "purple", "gray", "pink"],
    sizes: ["45", "46", "42", "40", "44"],
    description:
      "Sergio Lozano’s Air Max 95 is almost 30 years old, but it still looks fresh today. The designer, who’s also responsible for shoes like the Air Max 98 and Air Tuned Max, was inspired by human anatomy in creating the 95, looking to mimic the way the body’s bones, tissue, and joints connect and support one another. ",
    highlights: [
      "Durable Sole",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100%",
    ],
  },
];
export default products;
